version: "3.7"

services:
  web:
    build:
      context: ./fasm
      dockerfile: ./Dockerfile
    command: sh -c "python -m pytest"
    volumes:
      - "./fasm:/app"
    ports:
      - "8000:8000"
    healthcheck:
      test: "netstat -plutn | grep 0.0.0.0:8000"
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 4m30s
    depends_on:
      postgres:
        condition: service_healthy
      preloader:
        condition: service_completed_successfully
    env_file:
      - "./fasm/.env"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    networks:
      - ig_webapp

  preloader:
    build:
      context: ./fasm
      dockerfile: ./Dockerfile
    restart: on-failure
    healthcheck:
      test: "netstat -plutn | grep 0.0.0.0:8000"
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 4m
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "alembic upgrade head"
    env_file:
      - "./fasm/.env"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    networks:
      - ig_webapp

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "--dbname=${POSTGRES_DB}", "--username=${POSTGRES_USER}" ]
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 4m30s
    networks:
      - ig_webapp

networks:
  ig_webapp:
