"""add reviewer answer

Revision ID: 0a5ab9d0c228
Revises: 1e533d862be8
Create Date: 2023-12-03 19:47:50.996219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5ab9d0c228'
down_revision = '1e533d862be8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('reviewer_answer')

    # ### end Alembic commands ###
