"""Add review fields for question model

Revision ID: 0b62aafe5719
Revises: 69cabc9818ca
Create Date: 2023-11-29 12:19:50.150408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b62aafe5719'
down_revision = '69cabc9818ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_review', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('reviewed')
        batch_op.drop_column('for_review')

    # ### end Alembic commands ###
