"""add hint

Revision ID: 0ce798544d2e
Revises: 77c7c45e6ba3
Create Date: 2023-12-05 17:10:11.515076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce798544d2e'
down_revision = '77c7c45e6ba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('gpt_hint')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpt_hint', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('gpt_hint')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpt_hint', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
