"""test

Revision ID: e5c1b596407c
Revises: 5694e59f7e4f
Create Date: 2024-01-06 20:25:07.299587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c1b596407c'
down_revision = '5694e59f7e4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=200), nullable=True))
        batch_op.drop_index('users_cognito_id_idx')
        batch_op.drop_column('cognito_id')

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('verbs_eng_key'), ['eng'])

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('vocabulary_eng_key'), ['eng'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vocabulary_eng_key'), type_='unique')

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('verbs_eng_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognito_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_index('users_cognito_id_idx', ['cognito_id'], unique=False)
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
