"""Mark answer as nullable

Revision ID: 4567870d988e
Revises: 20d8ddb57df6
Create Date: 2023-11-27 18:28:29.812227

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4567870d988e'
down_revision = '20d8ddb57df6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
