"""vocabulary model

Revision ID: 4af7e330fef8
Revises: b04fcb088786
Create Date: 2023-12-10 07:59:05.309240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af7e330fef8'
down_revision = 'b04fcb088786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('eng', sa.String(length=100), nullable=False),
    sa.Column('farsi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('eng'),
    sa.UniqueConstraint('eng')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
