"""Add created_at to question model

Revision ID: 69cabc9818ca
Revises: 92c31e333c01
Create Date: 2023-11-28 15:09:32.879342

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '69cabc9818ca'
down_revision = '92c31e333c01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
