"""remove password

Revision ID: 6d9706df756b
Revises: b7e2750bb553
Create Date: 2023-11-26 10:49:31.755253

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6d9706df756b'
down_revision = 'b7e2750bb553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
