"""add hint

Revision ID: 737edd2ae46e
Revises: 0ce798544d2e
Create Date: 2023-12-05 17:37:50.536767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737edd2ae46e'
down_revision = '0ce798544d2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
