"""add hint

Revision ID: 77c7c45e6ba3
Revises: 94e05a0ed2a4
Create Date: 2023-12-05 17:08:37.278905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c7c45e6ba3'
down_revision = '94e05a0ed2a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpt_hint', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('gpt_hint')

    # ### end Alembic commands ###
