"""slug and more

Revision ID: 7ec8a1d54f8a
Revises: 6d9706df756b
Create Date: 2023-11-26 10:53:54.069305

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7ec8a1d54f8a'
down_revision = '6d9706df756b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
