"""Add user to question model

Revision ID: 92c31e333c01
Revises: def8ec37e83a
Create Date: 2023-11-28 14:48:06.269512

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '92c31e333c01'
down_revision = 'def8ec37e83a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
