"""add reviewer answer

Revision ID: 94e05a0ed2a4
Revises: 0a5ab9d0c228
Create Date: 2023-12-03 19:48:30.863907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e05a0ed2a4'
down_revision = '0a5ab9d0c228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
