"""verb model

Revision ID: b04fcb088786
Revises: 0ce798544d2e
Create Date: 2023-12-09 12:04:50.562954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04fcb088786'
down_revision = '0ce798544d2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng', sa.String(length=100), nullable=True),
    sa.Column('farsi', sa.String(length=100), nullable=True),
    sa.Column('stem', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng')
    )
    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verbs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verbs_id'))

    op.drop_table('verbs')
    # ### end Alembic commands ###
