"""Mark answer as nullable

Revision ID: def8ec37e83a
Revises: 4567870d988e
Create Date: 2023-11-27 19:03:34.093615

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'def8ec37e83a'
down_revision = '4567870d988e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gpt_answer', sa.Text(), nullable=True))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('gpt_answer')
        batch_op.drop_column('user_answer')

    # ### end Alembic commands ###
