"""Add section model

Revision ID: fa749cd33a70
Revises: 7ec8a1d54f8a
Create Date: 2023-11-26 10:59:07.942828

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fa749cd33a70'
down_revision = '7ec8a1d54f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_id'))

    op.drop_table('sections')
    # ### end Alembic commands ###
