name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > ./fasm/.env

      - name: Run tests
        run: |
          docker compose -f docker-compose.test.yml up --force-recreate --build --exit-code-from web web

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 3.94.1.12 >> ~/.ssh/known_hosts

      - name: Connect to EC2 and Restart Docker Compose
        run: |
          ssh ubuntu@3.94.1.12 'cd fasm && git pull && docker-compose up -d --build'
