name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 3.94.1.12 >> ~/.ssh/known_hosts

      - name: Connect to EC2 and Restart Docker Compose
        run: |
          ssh ubuntu@3.94.1.12
          cd fasm
          git pull
          docker-compose up -d --force-recreate
